### ISSUE TITLE
Why i can change my role?

### ISSUE THREAD

**Issue by realrashid** [drehimself/laravel-ecommerce-example#1]
Hi, i just visit the demo page and login as demo admin but i was clicked profile link and open profile edit page there i saw this :arrow_down: 
![roles](https://user-images.githubusercontent.com/15607685/36900019-6feb9154-1e43-11e8-9dd5-b36a21c2eb5e.PNG)

there i can changed my role to super admin
i think its voyager issue .

**Comment by drehimself** [comment]
Thanks for letting me know. Wow, that could be really dangerous in a real app. There's an open issue for this in Voyager: https://github.com/the-control-group/voyager/issues/2192. A temporary solution is to override the view and do some checks yourself. I'll add this in soon.

**Comment by realrashid** [comment]
yes i seen it and i also not satisfied with their permission system the-control-group/voyager#2192
