### ISSUE TITLE
Shipping/ Delivery charge

### ISSUE THREAD

**Issue by nasirkhan** [drehimself/laravel-ecommerce-example#13]
thanks for the awesome series. 

I was checking the project and tried to find a solution to add the Shipping/ Delivery charge at the checkout page. did you ended the series or have plan to cover that. Can you please guide me to find a solution to accommodate this cost with the cart.

**Comment by drehimself** [comment]
I am planning to use Shippo for this: https://laravel-news.com/shippo-multi-carrier-shipping-api-laravel-apps

I can't guarantee if or when I'm going to do it.
