### ISSUE TITLE
seeding

### ISSUE THREAD

**Issue by Simwenya** [drehimself/laravel-ecommerce-example#15]
application not seeding into database seeds only two tables users and migrations

**Comment by drehimself** [comment]
Are you using `php artisan ecommerce:install`?

**Comment by Simwenya** [comment]
yes

**Comment by Simwenya** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel-ecommerce-example.products' doesn't exist (SQL: select * from `products` where `featured` = 1 order by RAND() limit 8) i get this

**Comment by Simwenya** [comment]
![laravel](https://user-images.githubusercontent.com/26562287/40691959-3df0bda8-63af-11e8-8e94-fa4f16e30dfa.PNG)
thats my how my front page is appearing

**Comment by Simwenya** [comment]
i really need your help am new to this technology trying to integrate with react native

**Comment by thayronarrais** [comment]
I tried to follow the instructions but I got the same error
![image](https://user-images.githubusercontent.com/15815826/40693826-eaf3f530-638f-11e8-916a-5722aa992473.png)

so I run the php artisan migrate, with errors

[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table users add unique users_email_unique(email))

[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I fixed

![image](https://user-images.githubusercontent.com/15815826/40693858-15507074-6390-11e8-8308-03fbec9d6294.png)

I run php artisan migrate again, with errors but conclude 

![image](https://user-images.githubusercontent.com/15815826/40693889-36efd76a-6390-11e8-8eff-e8e58b0c0c0d.png)

now, php artisan ecommerce:install

![image](https://user-images.githubusercontent.com/15815826/40693919-57d38e18-6390-11e8-8d35-a5bdf088ba30.png)

php artisan serve

![image](https://user-images.githubusercontent.com/15815826/40693936-6ac8312c-6390-11e8-95d9-41ffbd20955f.png)


I fixed it, but I do not know the consequences in the project.

**Comment by Simwenya** [comment]
what class is that that

**Comment by thayronarrais** [comment]
AppServiceProvider.php

**Comment by Simwenya** [comment]
thanks now voyager is giving issues , hows yours working

**Comment by thayronarrais** [comment]
I have problems to save Settings in Voyager
:~

**Comment by drehimself** [comment]
Closing this issue since they are related to Voyager. I'm also having the same issue saving settings in Voyager.
