### ISSUE TITLE
Saving for later a product tampers the coupon value

### ISSUE THREAD

**Issue by davidrad13** [drehimself/laravel-ecommerce-example#17]
![image](https://user-images.githubusercontent.com/36671000/43214943-d71b9e5a-9008-11e8-9684-16073c6a0849.png)

**Comment by drehimself** [comment]
Thanks! I can't seem to reproduce this. Can you give me the exact steps you took to reach this point?

**Comment by davidrad13** [comment]
Of course, from scratch, add a product, then apply the coupon, after that add another product,and remove one of them. Coupon = 0.

Another case is remove all products, add a new one, the coupon is still avalaible, add another, repeat the procedure done before and the coupon will be tampered saving the discount from the product saved for later instead of the product remaining in cart.

![image](https://user-images.githubusercontent.com/36671000/43217668-38eca69a-9010-11e8-8585-c8233bc96c57.png)

**Comment by drehimself** [comment]
Fixed. Let me know if you still have issues.

**Comment by davidrad13** [comment]
Tested. It works perfectly thank you so much. If you don't mind I bother
mate, on my app I have an issue about saving for later and then moving back
to the cart, instead you don't have that issue. The issue is that when I
move the item back to the cart its value increases. Kinda like 142% of its
old value I have check the code exhaustively but can't seem to find what's
wrong. The only difference about our apps is that I use a second parameter
called total instead of price but I've replaced it everywhere from yours.
Maybe you can give me a direction of what may be wrong?

2018-07-25 19:41 GMT-04:00 Andre Madarang <notifications@github.com>:

**Comment by drehimself** [comment]
Check out my commit. This issue was quite tricky to debug and might be similar to what you are experiencing.

The problem was the cart events (add, update, remove) were firing on BOTH cart instances (I have a default cart and a "save for later" instance). I only want the events to fire (and therefore discount/price to update) on the default cart instance. So in my UpdateCoupon job, I have a check to only account for the default cart instance.

**Comment by drehimself** [comment]
If you haven't already, check out this video where I fix a similar bug: https://www.youtube.com/watch?v=vKan4b_r-Ew. I had to re-watch it myself to figure out what was going on 😅

**Comment by davidrad13** [comment]
Thanks Andre, yes, indeed I watched your fix bugs videos and what you did
in it works perfectly for me, my issue is that when I add a new product is
price being as example: 40000. then lets say I add 5 of them obviosuly it
changes to 200000.. then I decide to save that item for later, in the
saveforlater intance it shows the 40000 that one item is worth. But when I
move it back to the cart it saves the value of 200000 + 83220 more which is
like 1.415015 times its cost. I dont know why that happens, it happens even
if the product is just 1 quantity saved and moved again it increases it
costs. Please Andre I really sorry to bother but may you think in something
it may be which is causing that issue? I can see in your DEMO that you dont
have that problem. Thanks a lot for all the early and effective replies.
I've learned a lot from you

2018-07-26 10:51 GMT-04:00 Andre Madarang <notifications@github.com>:

**Comment by davidrad13** [comment]
By the way another tiny bug I found out is that the items we add from
Voyager, the route of the img must be changed on saveforlater cart.blade
section instead of  <a href="{{ route('shop.show', $item->model->slug) }}"><
img src="{{ asset('img/products/'.$item->model->slug.'.jpg') }}" alt="item"
class="cart-table-img"></a>

change it for :

<a href="{{ route('shop.show', $item->model->slug) }}"><img src="{{
productImage($item->model->image) }}" alt="item" class="cart-table-img"></a>

so the image can be showed on save for later items section

😀

2018-07-26 11:16 GMT-04:00 David Gonzalez <davidradofi@gmail.com>:
