### ISSUE TITLE
Admin / Voyager - Json error under database/products/bread/edit

### ISSUE THREAD

**Issue by cchau-tsgrp** [drehimself/laravel-ecommerce-example#2]
Under admin page, if you edit the products' bread, you will see an error in console which is `Uncaught SyntaxError: Unexpected token d in JSON at position 41`.
I believe bc of that, all "Optional Details" json area after the PRICE are "broken".
Thanks!

**Comment by cchau-tsgrp** [comment]
Maybe.... errors are inside the ProductsTableSeeder.php?
I'm not sure, still looking.

**Comment by drehimself** [comment]
Fixed. Needed an extra backslash when importing the regex from PHP.

**Comment by anilloutombam** [comment]
The error is still there
