### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by guilhermeureis** [drehimself/laravel-ecommerce-example#22]
I need to change the language to pt_br. How do I do that?

I have changed in 'locale' => 'en' to 'locale' => 'pt_br' and 'fallback_locale' => 'en' to 'fallback_locale' => 'pt_br' but not all translated

**Comment by WhereIsLucas** [comment]
The majority of the strings are hard-coded, you'll need to translate them by yourself in the views

**Comment by guilhermeureis** [comment]
Thanks, I had to do this myself.
