### ISSUE TITLE
Algolia Search error persistent

### ISSUE THREAD

**Issue by 000kelvin** [drehimself/laravel-ecommerce-example#24]
Hello, I've had issues with agolia search, I've removed the Searchable traits but trying to install it keeps telling me Algolia credentials incorrect. Your products table is NOT seeded correctly. If you are not using Algolia, remove Searchable trait from App\Product. I have performed composer dump-autoload, cleared the cache and all but nothing seems to work.

**Comment by 000kelvin** [comment]
I was able to solve the issue.

**Comment by Gbaguidi** [comment]
how did you do that i've the same problem

**Comment by muchirialex** [comment]
@000kelvin, How did you fix this?
