### ISSUE TITLE
Issue in Timestamp

### ISSUE THREAD

**Issue by williethai** [drehimself/laravel-ecommerce-example#25]
Hi all,

We are running this example on both Window and Linux machine. 

But get these error message:

`Exception thrown with message "DateTime::__construct(): Failed to parse time string (1) at position 0 (1): Unexpected character" 

Stacktrace: 
#61 Exception in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/nesbot/carbon/src/Carbon/Carbon.php:439 
#60 DateTime:__construct in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/nesbot/carbon/src/Carbon/Carbon.php:439 
#59 Carbon\Carbon:__construct in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/nesbot/carbon/src/Carbon/Carbon.php:476 
#58 Carbon\Carbon:parse in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/tcg/voyager/src/Http/Controllers/ContentTypes/Timestamp.php:21 
#57 TCG\Voyager\Http\Controllers\ContentTypes\Timestamp:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/tcg/voyager/src/Http/Controllers/Controller.php:204 
#56 TCG\Voyager\Http\Controllers\Controller:getContentBasedOnType in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/tcg/voyager/src/Http/Controllers/Controller.php:67 
#55 TCG\Voyager\Http\Controllers\Controller:insertUpdateData in /home/pi/Desktop/t/laravel-ecommerce-example/app/Http/Controllers/Voyager/ProductsController.php:290 
#54 App\Http\Controllers\Voyager\ProductsController:store in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 
#53 call_user_func_array in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 
#52 Illuminate\Routing\Controller:callAction in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 
#51 Illuminate\Routing\ControllerDispatcher:dispatch in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212 
#50 Illuminate\Routing\Route:runController in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169 
#49 Illuminate\Routing\Route:run in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659 
#48 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30 
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/tcg/voyager/src/Http/Middleware/VoyagerAdminMiddleware.php:27 
#46 TCG\Voyager\Http\Middleware\VoyagerAdminMiddleware:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 
#43 Illuminate\Routing\Middleware\SubstituteBindings:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67 
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63 
#34 Illuminate\Session\Middleware\StartSession:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59 
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 
#25 Illuminate\Pipeline\Pipeline:then in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Router.php:661 
#24 Illuminate\Routing\Router:runRouteWithinStack in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636 
#23 Illuminate\Routing\Router:runRoute in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Router.php:602 
#22 Illuminate\Routing\Router:dispatchToRoute in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Router.php:591 
#21 Illuminate\Routing\Router:dispatch in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176 
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30 
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/fideloper/proxy/src/TrustProxies.php:57 
#18 Fideloper\Proxy\TrustProxies:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30 
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30 
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46 
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149 
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/pi/Desktop/t/laravel-ecommerce-example/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 
#4 Illuminate\Routing\Pipeline:Illumin`

I think it is in the version of the Carbon api we are using, right ?

Thank you very much !!

**Comment by drehimself** [comment]
I am not sure, but check out this thread for similar issues with Carbon: https://github.com/briannesbitt/Carbon/issues/1173
