### ISSUE TITLE
No such Token

### ISSUE THREAD

**Issue by bkerberos** [drehimself/laravel-ecommerce-example#26]
Help 
![image](https://user-images.githubusercontent.com/30532126/45981289-1a6f8900-c01a-11e8-9025-9866703bc807.png)

**Comment by akkhan20** [comment]
what was the issue? im facing the same issue :(

**Comment by bkerberos** [comment]
Change your Pk_test that gives you stripe in the file
-> "checkout.blade.php"
      line number 169 -> "var stripe = Stripe ('change here');

![image](https://user-images.githubusercontent.com/30532126/46260046-cf84c400-c4a6-11e8-9e1c-f8522e7dc3e8.png)


By the way it has to be the same as the one you configured in your .env

**Comment by akkhan20** [comment]
@bkerberos Thank you very much :)
