### ISSUE TITLE
Algolia credentials incorrect

### ISSUE THREAD

**Issue by Hein-Thu-Ya** [drehimself/laravel-ecommerce-example#32]
Algolia credentials incorrect. Your products table is NOT seeded correctly. If y
ou are not using Algolia, remove Searchable trait from App\Product
Algolia credentials incorrect. Check your .env file.

**Comment by ianrizh** [comment]
Even when i removed the "Searchable trait" i still get the same error. How to fix this?

**Comment by drehimself** [comment]
If you're not using Algolia, remove `Laravel\Scout\Searchable` from `App\Product`.

If you are using Algolia, make sure your .env file has valid keys and values for `ALGOLIA_APP_ID` and `ALGOLIA_SECRET`

**Comment by teslun** [comment]
I have the same problem with "Algolia credentials incorrect". This is because "Access denied for user 'homestead'@'localhost' to database". After that, I change the SQL user to "root" in .env. Algolia credentials works.
