### ISSUE TITLE
proceed to checkout

### ISSUE THREAD

**Issue by ideadigitalindonesia** [drehimself/laravel-ecommerce-example#34]
when i pressed the button proceed to checkout i got error Braintree \ Exception \ Configuration
Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway).

**Comment by ideadigitalindonesia** [comment]
![error](https://user-images.githubusercontent.com/33254564/49153118-d1baa180-f2e2-11e8-992b-54817c895c0c.png)

**Comment by drehimself** [comment]
Fixed. Added try/catch if you don't have Braintree credentials set. Also updated readme.
