### ISSUE TITLE
User Bread Error

### ISSUE THREAD

**Issue by Loremlpsum** [drehimself/laravel-ecommerce-example#37]
Trying to get property of non-object

![issue-laravel-ecommerce](https://user-images.githubusercontent.com/45778141/51020636-1a3fcd00-15ba-11e9-8f31-70f20b6df6df.png)

**Comment by SV-RAJA** [comment]
verb check python checking for Python executable "python2" in the PATH

**Comment by SV-RAJA** [comment]
Error when installing npm install
 How to solve it

**Comment by marpal71** [comment]
just installed. SAME problem

**Comment by drehimself** [comment]
Just updated to L5.8. Should be fixed now.
