### ISSUE TITLE
App\Http\Controllers\Voyager\ProductsController::getRelationships does not exist.

### ISSUE THREAD

**Issue by donchi4all** [drehimself/laravel-ecommerce-example#39]
![error](https://user-images.githubusercontent.com/33794017/52517644-7ab83d80-2c3e-11e9-9141-72579122e6d1.PNG)

I have been having this error for some months now please help me fix it

**Comment by workproject** [comment]
me too

**Comment by workproject** [comment]
https://github.com/the-control-group/voyager/pull/3836

**Comment by drehimself** [comment]
Just updated everything to L5.8. This should be fixed now.
