### ISSUE TITLE
Admin/Voyager - Json error under database/admin/products/create

### ISSUE THREAD

**Issue by anilloutombam** [drehimself/laravel-ecommerce-example#46]
![Screenshot (71)](https://user-images.githubusercontent.com/23106365/57426075-8a462300-723b-11e9-80b6-7e047dab374e.png)

json_decode() expects parameter 1 to be string, object given

Unable to add product

**Comment by anilloutombam** [comment]
it was a huge bugs but fixed it anyways

**Comment by necatisen** [comment]
@anilloutombam how did you solve the error I got the same error?

**Comment by anilloutombam** [comment]
> @anilloutombam how did you solve the error I got the same error?
are you also facing the same issue..if thn let me review my code..it's been a long time

**Comment by necatisen** [comment]
@anilloutombam  I am sharing the error again. maybe you remember.

[![image](https://i.hizliresim.com/zy2o7j.png)](https://hizliresim.com/zy2o7j)
