### ISSUE TITLE
AlgoliaSearch requires an applicationID

### ISSUE THREAD

**Issue by mysykez** [drehimself/laravel-ecommerce-example#5]
![screenshot from 2018-04-05 20-48-39](https://user-images.githubusercontent.com/12390910/38369981-358e2dd8-3913-11e8-99f5-eb7cbc88657c.png)

im fresh install your application from github clone
php artisan ecommerce:install error algoliasearch requires applicationID
and im try rollback . and tri install manual migrate sucsess and db:seed eror algoliasearch requires applicationID
help pls

**Comment by drehimself** [comment]
Enter correct Algolia credentials in .env file (ALGOLIA_APP_ID, ALGOLIA_SECRET).

If not using Algolia, remove the "Searchable" trait (Laravel Scout) in App\Product model.

**Comment by peterwanjiru** [comment]
create an account with algolia and get your Appkey and product key there.
