### ISSUE TITLE
I'm getting an error when i add products to the cart , using hardevine/LaravelShoppingcart

### ISSUE THREAD

**Issue by phaniophrero** [drehimself/laravel-ecommerce-example#74]
Hi , I'm gettig an error when i try to submit an product to the cart in the product page , I'm at the 5-6th episode on YouTube I just did the coupons and then I realised that i can't add products anymore to the cart . I'll attach an screen shot to see my error.
Thank you in advance !
![error identifier](https://user-images.githubusercontent.com/49799614/72255078-22d04680-3606-11ea-98c1-9b3433af4fae.png)

**Comment by jhoanborges** [comment]
hello.  can you paste the cart::add method and variables?
