### ISSUE TITLE
 Problem adding to cart, 

### ISSUE THREAD

**Issue by JulianCosta11** [drehimself/laravel-ecommerce-example#83]
trying to add a product to the cart returns this error:
ErrorException
Trying to access array offset on value of type null.

C:\xampp\htdocs\ecommerce\app\Listeners\CartUpdatedListener.php:30

in line 30:   $couponName = session()->get('coupon')['name'];

translated by Google.

**Comment by TharinduX** [comment]
How did you fix this? I have the same problem.

**Comment by risanviargi** [comment]
Hello, I have the same problem too. Still searching the answer around, would you mind to tell us how did you fix this?

**Comment by Martin-1182** [comment]
How did you fix this? I have the same problem.

**Comment by TharinduX** [comment]
$couponName = null;

 if (session()->get('coupon')) {
           $couponName = session()->get('coupon')['name'];
}

if ($couponName) {
      $coupon = Coupon::where('code', $couponName)->first();

     dispatch_now(new UpdateCoupon($coupon));
}
