### ISSUE TITLE
ErrorException Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Shayboniyshoh** [drehimself/laravel-ecommerce-example#98]
public function handle($event)

    {

        $couponName = session()->get('coupon')['name'];

 

        if ($couponName) {

            $coupon = Coupon::where('code', $couponName)->first();

 

            dispatch_now(new UpdateCoupon($coupon));

        }

    }

I have following error when I click to "Add To Cart" button: ErrorException
Trying to access array offset on value of type null.

it points me to the following line of code which I pasted above, and it is the peace of code inside CardUpdateListener.php:$couponName = session()->get('coupon')['name'];

**Comment by Martin-1182** [comment]
$couponName = session()->get('coupon')['name'] ?? null;
